server:
    port: 8080

logging:
    level:
        root: info

spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        url: jdbc:mysql://localhost:3306/rfid-realtime-monitoring-2
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        defer-datasource-initialization: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            javax.persistence.validation.mode: none
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
    sql:
        init:
            mode: embedded